name: merchant
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  get: ^4.6.5
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.10
  share_plus: ^10.1.3
  country_code_picker: ^3.1.0
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.3.5
  timelines: ^0.1.0
  intl_phone_field: ^3.2.0
  dropdown_textfield: ^1.2.0
  splash_view: ^2.0.1
  dio: ^5.7.0
  path: ^1.8.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  easy_localization: ^3.0.0
  flutter_html: ^3.0.0
  file_picker: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - lib/services/app_translation.dart


  fonts:
    - family: Roboto Black
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf

    - family: Roboto Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Roboto Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: Roboto Italic
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf

    - family: Roboto Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf